Feature/rebuild plugin
corne-de-bruin/nativescript-pdf-view pull request #1
Opened 2017-01-18 12:45 UTC by jboeijenga

2017-01-18 13:45 UTC, spike1292 requested changes

2017-01-18 13:45 UTC, spike1292 commented on demo/app/App_Resources/Android/app.gradle
> +    // ndk {
remove commented code?

2017-01-18 13:45 UTC, spike1292 commented on package.json
> -  "repository": {
pls add needed for npm

2017-01-18 13:45 UTC, spike1292 commented on package.json
> +  "main": "pdfviewer.js",
remove the js extension, nativescript doesn't like it

2017-01-18 13:45 UTC, spike1292 commented on package.json
> +  "name": "ns-pdfviewer",
think the old name is good, but then we need to come up with a beter package name for example`nativescript-pdf-viewer-xcode-8`

2017-01-18 13:45 UTC, spike1292 commented on package.json
> -  "keywords": [
pls add needed for npm

2017-01-18 13:45 UTC, spike1292 commented on pdfviewer.common.ts
> +		console.log('pdf viewer load url: ' + src);
console.log?

2017-01-18 13:45 UTC, spike1292 commented on pdfviewer.ios.ts
> +function iosProperty(theClass, theProperty) {
👍

2017-01-18 13:45 UTC, spike1292 commented on src/plugin.common.ts
> -try {
why is this removed?

2017-01-18 13:45 UTC, spike1292 commented on index.d.ts
> +export * from './pdfviewer.common';
add 
`export * from './pdfviewer.ios'`

2017-01-18 13:45 UTC, spike1292 commented on pdfviewer.common.ts
> +	public static notifyOfEvent(eventName: string, pdfViewRef: WeakRef<PdfViewer>) {
not used so can it be removed?

2017-01-18 13:45 UTC, spike1292 commented on platforms/android/include.gradle
> +    "ns-pdfviewer" {
if the packagename is changed, dont forget this

2017-01-18 14:02 UTC, dennis-montana approved these changes

2017-01-23 16:14 UTC, spike1292 commented on demo/package.json
> +    "nativescript-pdf-viewer": "file:///Users/Henk/Projects/nativescript/nativescript-pdf-view",
remove

2017-01-23 16:19 UTC, spike1292 approved these changes

2017-01-23 16:19 UTC, merged